config/routes.rb
require 'resque/server'


CodeTriage::Application.routes.draw do
  get "users/sign_in" => redirect('/users/auth/github'), via: [:get, :post]
  get "users/sign_up" => redirect('/users/auth/github'), via: [:get, :post]

  devise_for  :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks",  registrations: "users"}

  root        to: "pages#index"

  namespace :users do
    resources :after_signup
  end

  resources   :users
  get         "/users/unsubscribe/:account_delete_token" => "users#token_delete", as: :token_delete_user
  delete      "/users/unsubscribe/:account_delete_token" => "users#token_destroy"

  resources   :issue_assignments

  get "/issue_assignments/:id/users/:user_id/click", to: "issue_assignments#click_redirect", as: :issue_click

  resources   :repo_subscriptions

  if Rails.env.development?
    mount UserMailer::Preview => 'mail_view'
  end

  mount Resque::Server.new, at: "/codetriage/resque"

  # format: false gives us rails 3.0 style routes so angular/angular.js is interpreted as
  # user_name: "angular", name: "angular.js" instead of using the "js" as a format
  scope format: false do
    resources :repos, only: %w[index new create]

    scope '*full_name' do
      constraints full_name: REPO_PATH_PATTERN do
        get   '/',            to: 'repos#show',        as: 'repo'
        patch '/',            to: 'repos#update',      as:  nil
        get   '/edit',        to: 'repos#edit',        as: 'edit_repo'
        get   '/subscribers', to: 'subscribers#show',  as: 'repo_subscribers'
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include ResqueDef

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable

  validates_uniqueness_of :email,    allow_blank: true, if: :email_changed?
  validates_length_of     :password, within:  8..128, allow_blank: true
  validates :github, presence: true, uniqueness: true

  # Setup accessible (or protected) attributes for your model

  has_many :repo_subscriptions, dependent: :destroy
  has_many :repos, through: :repo_subscriptions

  has_many :issue_assignments, through: :repo_subscriptions
  has_many :issues,            through: :issue_assignments

  scope :public_profile, -> { where.not(users: { private: true }) }

  alias_attribute :token, :github_access_token

  delegate :for, to: :repo_subscriptions, prefix: true
  before_save :set_default_last_clicked_at

  def set_default_last_clicked_at
    self.last_clicked_at ||= Time.now
  end

  def auth_is_valid?
    GitHubBub.valid_token?(token)
  end

  def self.random
    order("RANDOM()")
  end

  # users that are not subscribed to any repos
  def self.inactive
    joins("LEFT OUTER JOIN repo_subscriptions on users.id = repo_subscriptions.user_id").where("repo_subscriptions.user_id is null")
  end

  def default_avatar_url
    "http://gravatar.com/avatar/default"
  end

  def account_delete_token
    if self[:account_delete_token].blank?
      self.account_delete_token = SecureRandom.hex(64)
      update_attribute(:account_delete_token, account_delete_token) unless new_record?
    end

    super
  end

  def enqueue_inactive_email
    background_inactive_email(self.id)
  end

  def able_to_edit_repo?(repo)
    repo.user_name == github.downcase
  end

  def public?
    !private
  end

  def not_yet_subscribed_to?(repo)
    !subscribed_to?(repo)
  end

  def subscribed_to?(repo)
    sub_from_repo(repo).present?
  end

  def sub_from_repo(repo)
    self.repo_subscriptions.find_by(repo_id: repo.id)
  end

  def github_json
    GitHubBub.get(api_path, token: self.token).json_body
  end

  def fetch_avatar_url
    github_json["avatar_url"]
  end

  def set_avatar_url!
    self.avatar_url = self.fetch_avatar_url || default_avatar_url
    self.save!
  end

  def self.find_for_github_oauth(auth, signed_in_resource=nil)
    user  = signed_in_resource ||
            User.find_by(github: auth.info.nickname) ||
            User.find_by(email:  auth.info.email)

    token = auth.credentials.token
    params = {
      github:              auth.info.nickname,
      github_access_token: token,
      avatar_url: auth.extra.raw_info.avatar_url
    }

    if user
      user.update_attributes(params)
    else
      email =  auth.info.email
      email =  GitHubBub.get("/user/emails", token: token).json_body.first if email.blank?
      params = params.merge(password: Devise.friendly_token[0,20],
                            name:     auth.extra.raw_info.name,
                            email:    email)
      user = User.create(params)
    end
    user
  end

  def github_url
    "https://github.com/#{github}"
  end

  def api_path
    "/user"
  end

  def valid_email?
    ValidateEmail.valid?(email)
  end

  resque_def(:background_inactive_email) do |id|
    user = User.find(id.to_i)
    return false if user.repo_subscriptions.present?
    UserMailer.poke_inactive(user).deliver_now
  end

  def days_since_last_clicked
    return 0 if last_clicked_at.blank?
    (
      (Time.now - last_clicked_at) / 1.day
    ).to_i # only want whole days
  end

  def days_since_last_email
    last_sent_at = repo_subscriptions.last.try(:last_sent_at)
    last_sent_at ||= self.created_at
    (
      (Time.now - last_sent_at) / 1.day
    ).to_i # only want whole days
  end

  def send_daily_triage!
    return false if repo_subscriptions.blank?
    skip = EmailDecider.new(days_since_last_clicked).skip?(days_since_last_email)
    puts "User #{github}: skip: #{skip.inspect}, days_since_last_clicked: #{days_since_last_clicked}, days_since_last_email: #{days_since_last_email}"
    return false if skip

    IssueAssigner.new(self, repo_subscriptions).assign
    ids         = repo_subscriptions.pluck(:id)
    assignments = IssueAssignment.where(repo_subscription_id: ids).where(delivered: false).limit(daily_issue_limit)
    if assignments.present?
      assignments.update_all(delivered: true)
      repo_subscriptions.update_all(last_sent_at: Time.now)
      UserMailer.send_daily_triage(user: self, assignments: assignments).deliver_now
    end
  end

  resque_def(:delay_send_daily_triage_email) do |id|
    User.find(id).send_daily_triage!
  end

  def favorite_language?(language)
    favorite_languages.include? language if favorite_languages
  end

  def has_favorite_languages?
    favorite_languages && !favorite_languages.empty?
  end

  end

app/controllers/users/after_signup_controller.rb
class Users::AfterSignupController < ApplicationController

  include Wicked::Wizard

  before_filter :authenticate_user!

  steps :set_privacy

  def show
    @user = current_user
    render_wizard
  end

  def update
    @user = current_user
    @user.update_attributes(user_params)
    render_wizard @user
  end

  private

    def user_params
      params.require(:user).permit(
        :private,
        :email,
        :password,
        :password_confirmation,
        :remember_me,
        :zip,
        :phone_number,
        :twitter,
        :github,
        :github_access_token,
        :avatar_url,
        :name,
        :favorite_languages,
        :daily_issue_limit
        )
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github
    @user = User.find_for_github_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      if @user.valid_email?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", kind: "GitHub"
      else
        flash[:notice] = I18n.t "devise.omniauth_callbacks.bad_email_success", kind: "GitHub"
      end

      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.github_data"] = request.env["omniauth.auth"].delete("extra")
      flash[:error]  = no_email_error if request.env["omniauth.auth"].info.email.blank?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.failure",
                       kind: "GitHub", reason: "Invalid credentials" if flash[:error].blank?
      redirect_to root_path
    end
  end

  private

  def no_email_error
    msg =  "You need a public email address on GitHub to sign up you can add"
    msg << " an email, sign up for triage, then remove it from GitHub:<hr />"
    msg << "<a href='https://github.com/settings/profile'>GitHub Profile</a>"
    msg.html_safe
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, only: [:update, :destroy]

  def show
    @user = User.find(params[:id])
    if @user.private?
      redirect_to root_path unless current_user && @user == current_user
    end
  end

  def edit
    @user = current_user
  end

  def update
    begin
      uparams = user_params
    rescue ActionController::ParameterMissing
      uparams = {favorite_languages: []}
    end

    @user = current_user
    if @user.update_attributes(uparams)
      redirect_to @user, flash: { success: 'User successfully updated' }
    end
  end

  def destroy
    @user = current_user
    @user.destroy
    redirect_to root_url, notice: "Successfully removed your user account"
  end

  def token_delete
    @user = User.find_by(account_delete_token: params[:account_delete_token])
    if @user.nil?
      redirect_to root_url, notice: "Account could not be found. You may have already deleted it, or your GitHub username may have changed."
    end
  end

  def token_destroy
    @user = User.find_by(account_delete_token: params[:account_delete_token])
    @user.destroy
    redirect_to root_url, notice: "Successfully removed your user account"
  end

  private

    def user_params
      params.require(:user).permit(
        :private,
        :email,
        :password,
        :password_confirmation,
        :remember_me,
        :zip,
        :phone_number,
        :twitter,
        :github,
        :github_access_token,
        :avatar_url,
        :name,
        :daily_issue_limit,
        :skip_issues_with_pr,
        favorite_languages: []
        )
    end
end

app/views/users/_form.html.slim
.clearfix
  = f.label :email, t("activerecord.attributes.user.email", default: "Email"), class: "label label-info"
  .controls
    .input-prepend
      span.add-on
        i.icon-envelope
      = f.text_field :email, class: 'text_field'
  = f.label :daily_issue_limit, t("activerecord.attributes.user.daily_issue_limit", default: "Max # of issues you want to receive per day"), class: "label label-info"
  .input
    = f.number_field :daily_issue_limit, class: 'number_field', min: 0
  => f.label :skip_issues_with_pr, t("activerecord.attributes.user.skip_issues_with_pr", default: "Skip Issues with Pull requests"), class: "label label-info"
  = f.check_box :skip_issues_with_pr, class: 'checkbox'
.form-actions
  => button_tag "Save", class: "btn btn-success"
  ' or
  = link_to "Cancel", :back, class: "btn btn-danger"

app/views/users/edit.html.slim
= form_for @user, url: user_path(@user), method: :patch, html: { class: "edit_user", id: "edit_user" } do |f|
  = render partial: "form", locals: {f: f}

app/views/users/new.html.slim
= form_for @user, url: users_path, html: { class: :form } do |f|
  = render partial: "form", locals: {f: f}

app/views/users/show.html.slim
.span8
  h2= @user.github
  - if current_user.blank?
    | Are you #{@user.github}?
    br
    span.active= link_to 'Login', new_user_registration_path
    | to edit your account
  - if current_user && current_user == @user
    section#user-details
      h5 Email : #{@user.email}
      small.muted Only visible to you
      h5 Publicly visible? : #{@user.public? ? "Yes" : "No"}
      - if @user.public?
        = link_to "Stay private", users_path(user: {private: true}), method: :put, class: 'btn btn-warning'
      - else
        = link_to "Go public", users_path(user: {private: false}), method: :put, class: 'btn btn-success'
      h5 Max # of issues you want to receive per day: #{@user.daily_issue_limit.presence || 'not set'}
      h5 Skip Issues with Pull Requests: #{@user.skip_issues_with_pr}
    section#user-favorite-langs
      h3 Favorite Languages:
      p Select your favorite languages:
      = form_for @user do |f|
        - Repo.all_languages.each do |language|
          label.checkbox
            = f.check_box :favorite_languages, { multiple: true }, language, nil
            = language
        p= button_tag "Save", class: "btn btn-primary"
  .form-actions
    - if current_user.blank?
      | Are you #{@user.github}?
      br
      span.active= link_to 'Login', new_user_registration_path
      | to edit your account
    - elsif current_user == @user
      => link_to '<i class="icon-edit icon-white"></i> Edit my Account'.html_safe, edit_user_path(@user), class: 'btn btn-primary', style: 'margin-bottom: 5px'
      = link_to '<i class="icon-trash icon-white"></i> Delete my account'.html_safe, user_path(@user), method: "delete", confirm: "#{t("web-app-theme.confirm", default: "Are you sure?")}", class: 'btn btn-danger'
    - else
      | This isn't your account, jump to #{link_to current_user.github, current_user}

app/views/users/token_delete.html.slim
.alert.alert-error
  | Are you sure you want to delete your account and stop receiving triage emails at
  strong= @user.email
  | ?
= form_for @user, url: token_delete_user_path(@user.account_delete_token), method: :delete, html_options: { class: "form form-horizontal" } do |f|
  = f.submit "Yes, Delete My Account", class: "btn btn-danger"
  = link_to "No, Cancel", root_url, class: "btn"