config/routes.rb
require 'resque/server'


CodeTriage::Application.routes.draw do
  get "users/sign_in" => redirect('/users/auth/github'), via: [:get, :post]
  get "users/sign_up" => redirect('/users/auth/github'), via: [:get, :post]

  devise_for  :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks",  registrations: "users"}

  root        to: "pages#index"

  namespace :users do
    resources :after_signup
  end

  resources   :users
  get         "/users/unsubscribe/:account_delete_token" => "users#token_delete", as: :token_delete_user
  delete      "/users/unsubscribe/:account_delete_token" => "users#token_destroy"

  resources   :issue_assignments

  get "/issue_assignments/:id/users/:user_id/click", to: "issue_assignments#click_redirect", as: :issue_click

  resources   :repo_subscriptions

  if Rails.env.development?
    mount UserMailer::Preview => 'mail_view'
  end

  mount Resque::Server.new, at: "/codetriage/resque"

  # format: false gives us rails 3.0 style routes so angular/angular.js is interpreted as
  # user_name: "angular", name: "angular.js" instead of using the "js" as a format
  scope format: false do
    resources :repos, only: %w[index new create]

    scope '*full_name' do
      constraints full_name: REPO_PATH_PATTERN do
        get   '/',            to: 'repos#show',        as: 'repo'
        patch '/',            to: 'repos#update',      as:  nil
        get   '/edit',        to: 'repos#edit',        as: 'edit_repo'
        get   '/subscribers', to: 'subscribers#show',  as: 'repo_subscribers'
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    if !resource.valid_email?
      edit_user_path(resource)
    elsif resource.new_record?
      users_after_signup_index_path
    else
      request.env['omniauth.origin'] || stored_location_for(resource) || root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then 'info'
    when :error then 'error'
    when :alert then 'warning'
    end
  end
end

app/views/application/_flashes.html.slim
- [:notice, :error, :alert, :success].each do |level|
  - unless flash[level].blank?
    div class="alert alert-block alert-#{level}"
      a.close href="#" data-dismiss="alert"
        | &times;
      = content_tag :p, flash[level]

app/views/application/_footer.html.slim
hr

.container
  .row-fluid
    .span4
    .span8
      / <iframe src="https://ghbtns.com/github-btn.html?user=codetriage&repo=codetriage&type=watch&count=true&v=2" frameborder="0" scrolling="0" width="100px" height="20px"></iframe>
      / <iframe src="https://ghbtns.com/github-btn.html?user=codetriage&repo=codetriage&type=star&count=true" frameborder="0" scrolling="0" width="100px" height="20px"></iframe>
      / <iframe src="https://ghbtns.com/github-btn.html?user=codetriage&repo=codetriage&type=fork&count=true" frameborder="0" scrolling="0" width="100px" height="20px"></iframe>
    p.text-center &copy BugTriage 2015

app/views/application/_head.html.slim
head
  meta charset="utf-8"
  title Bug Triage

  meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"
  meta name="viewport" content="width=device-width, initial-scale=1.0"
  = csrf_meta_tags

  = stylesheet_link_tag "application", media: "all"

  script src="http://heroku.github.com/template-app-bootstrap/jquery-1.7.1.min.js"
  script src="http://heroku.github.com/template-app-bootstrap/jquery.replacetext.min.js"
  = javascript_include_tag "application"

  /! IMPORTANT:
     This is Heroku specific styling. Remove to customize.
  link href="http://heroku.github.com/template-app-bootstrap/heroku.css" rel="stylesheet"
  /! ///

app/views/application/_nav.html.slim
.masthead
  ul.nav.nav-pills.pull-right
    - if user_signed_in?
      li= link_to "Home", root_path
      li= link_to  "Repos", repos_path
      li= link_to current_user.github, current_user
      li= image_tag current_user.avatar_url, class: 'img-rounded', height: 30, width: 30
      li= link_to "Sign Out", destroy_user_session_path, method: :delete
    - else
      li= link_to "Home", root_path
      li.active
        = link_to 'Sign in', new_user_registration_path
  h3.muted
    = link_to "Bug Triage", root_path

app/views/application/_repos.html.slim
- lang_index = 0
.row-fluid
  ul.nav.nav-tabs.nav-stacked.span4#repo-tabs data-tabs="tabs"
    - repos.group_by(&:language).each do |lang, repos|
      - unless lang == nil
        li = link_to lang, "##{lang.parameterize}#{lang.hash}", data: { toggle: "tab" }
  .tab-content.span8
    - repos.group_by(&:language).each do |lang, repos|
      - unless lang == nil
        div class="tab-pane#{" active" if lang_index == 0}" id="#{lang.parameterize}#{lang.hash}"
          ul.unstyled.repos-list = render repos
        - lang_index = lang_index + 1

= link_to "Submit a Repo", new_repo_path, class: 'btn btn-success'

javascript:
  $(document).ready(function(){
    var hash = document.location.hash;

    if (hash) {
      $('.nav-tabs a[href='+hash+']').tab('show');
    }
  });